/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ly_jniandbreaddemo_MainActivity */

#ifndef _Included_com_ly_jniandbreaddemo_MainActivity
#define _Included_com_ly_jniandbreaddemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ly_jniandbreaddemo_MainActivity
 * Method:    initBreakpadNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ly_jniandbreaddemo_MainActivity_initBreakpadNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ly_jniandbreaddemo_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ly_jniandbreaddemo_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
