/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myapp_com_jnidemo_MainActivity */

#ifndef _Included_myapp_com_jnidemo_MainActivity
#define _Included_myapp_com_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     myapp_com_jnidemo_MainActivity
 * Method:    setupNativeCrashesListener
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_ly_jniandbreaddemo_MainActivity_setupNativeCrashesListener
  (JNIEnv *, jobject, jstring);

JNIEXPORT void Java_com_ly_jniandbreaddemo_MainActivity_nativeCrash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
